import '../scss/main.scss'

import './sliders'
import './sliderControls'
import './productFeatures'
import './inputs'
import './header'
import './topBtn'
import './aos'
import './messengers'
import './anchors'
import './linksWidth'